name = "kaizenhub"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "kaizenhub-db"
database_id   = "d3ceaf74-7d29-41d0-b8f6-672903a978bf"   # ← replace after: wrangler d1 create kaizenhub-db
